#!/bin/bash
systemctl daemon-reload
echo "Enabling cloud-torrent daemon service."
if [[ -f "/lib/systemd/system/cloud-torrent.service" ]]; then
    systemctl enable cloud-torrent.service
fi
if [[ -f "/etc/init.d/cloud-torrent" ]]; then
    update-rc.d cloud-torrent defaults
fi
